### ISSUE TITLE
ReadMe explication is incorrect

### ISSUE THREAD

**Issue by eapuertoc** [ladybug-tools/ladybug-pandas#154]
The instructions about how to use the code in ReadMe are incorrect, it should say:
```python
import ladybug_pandas as lbp
from ladybug.epw import EPW

epw_path = 'tokyo.epw'
epw = EPW(epw_path)
epw._import_data()
df = lbp.DataFrame.from_epw(epw)
df_ip = df.ladybug.to_ip()
```

**Comment by AntoineDao** [comment]
Hi @eapuertoc! Thanks for spotting this issue with documentation. I will try to spend time to review this and patch a fix over the weekend. 

Alternatively it would be super helpful if you could submit a Pull Request to this repository with proposed corrections 🙌

**Comment by eapuertoc** [comment]
Sorry, I'm new in this things, I didn't know how to pull request, but I'll be practicing, I hope to participate more in your projects, they're very useful. Regards.

**Comment by AntoineDao** [comment]
No worries! Happy to help along the way if needed. You might find [this guide](https://guides.github.com/introduction/flow/) helpful to get yourself started on your GitHub journey!
